adventure/urls.py
import os

from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.static import serve

import home.views

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', RedirectView.as_view(url='explore/', permanent=False), name='index'),
    path('admin/', admin.site.urls),
    path('explore/', include('explore.urls')), 
    path('api/explore/', include('explore.api_urls')),
    path('items/', include('item.urls')),
    path('player/', include('player.urls')),
    path('accounts/register', home.views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('guide/', TemplateView.as_view(template_name='home/guide.html'), name='guide'),
]

explore/urls.py
from django.urls import path
from . import views

app_name = 'explore'
urlpatterns = [
        path('', views.index, name='index'),
        path('lobby/', views.lobby, name='lobby'),
        path('create/', views.create_area, name='create_area'),
        path('create/<area_title>', views.create_area, name='create_area'),
        path('<int:area_id>/', views.area, name='area'),
        path('<int:area_id>/edit', views.edit_area, name='edit_area'),
        path('<int:source_id>/connection/<title>', views.new_connection, name='new_connection'),
        path('<int:source_id>/connection/<title>/edit', views.edit_connection, name='edit_connection'),
        path('<int:source_id>/connection/<title>/delete', views.delete_connection, name='delete_connection'),
        path('<int:area_id>/activity/<int:activity_id>/delete', views.delete_activity, name='delete_activity'),
        # Legacy paths, should not be used in new code
        path('<int:area_id>/description', views.edit_area, name='area_description'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
        path('create/<int:area_id>', views.create, name='create'),
        path('<int:item_id>/delete', views.delete, name='delete'),
]

home/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST, label_suffix='')
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            url = request.POST.get('next', reverse('explore:index'))
            return HttpResponseRedirect(url)
    else:
        form = UserCreationForm(label_suffix='')
    return render(request, 'registration/register.html', {'form': form})

home/templates/base.html
{% load static %}
<html>
  <head>
    <title>
      Adventure.TXT
      {% if subtitle %}
      : {{ subtitle }}
      {% endif %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title"              content="Adventure.TXT" />
    {% block og_description %}<meta property="og:description"        content="Welcome to Adventure.TXT, a collaborative multiplayer text adventure. The game and story are created by the users, and always evolving. Your score increases as other players interact with parts of the world you create. Keep an eye out on the lobby for news about new features." />{% endblock %}
  </head>
  <body>
    <div id="container" class="container">
      <h1><a href="{% url 'explore:lobby' %}">Adventure.TXT</a></h1>
      {% block dashboard %}
      {% endblock %}
      {% block content %}
      {% endblock %}
      <div id="footer">
      {% block footer %}
        <p>
          <a href="/guide">Adventure.TXT Player's Guide</a>.<br/>
          Written as an example for <a href="https://dj4e.com/">SI 664</a>.<br/>
          Inspired by classic MUDs like <a href="https://en.wikipedia.org/wiki/LambdaMOO">LambdaMOO</a>.<br/>
          <a href="https://github.com/elplatt/Adventure664">Code</a> Copyright (C) Edward L. Platt 2020&#8212;2022, distributed under <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPL 3.0</a>.<br/>
          Questions or Comments? &lt;ed@elplatt.com&gt;
        </p>
      {% endblock %}
      </div>
    </div>
    {% block scripts %}
    {% endblock %}
  </body>
</html>