adventure/urls.py
import os

from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.static import serve

import home.views

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', RedirectView.as_view(url='explore/', permanent=False), name='index'),
    path('admin/', admin.site.urls),
    path('explore/', include('explore.urls')), 
    path('api/explore/', include('explore.api_urls')),
    path('items/', include('item.urls')),
    path('player/', include('player.urls')),
    path('accounts/register', home.views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('guide/', TemplateView.as_view(template_name='home/guide.html'), name='guide'),
]

explore/urls.py
from django.urls import path
from . import views

app_name = 'explore'
urlpatterns = [
        path('', views.index, name='index'),
        path('lobby/', views.lobby, name='lobby'),
        path('create/', views.create_area, name='create_area'),
        path('create/<area_title>', views.create_area, name='create_area'),
        path('<int:area_id>/', views.area, name='area'),
        path('<int:area_id>/edit', views.edit_area, name='edit_area'),
        path('<int:source_id>/connection/<title>', views.new_connection, name='new_connection'),
        path('<int:source_id>/connection/<title>/edit', views.edit_connection, name='edit_connection'),
        path('<int:source_id>/connection/<title>/delete', views.delete_connection, name='delete_connection'),
        path('<int:area_id>/activity/<int:activity_id>/delete', views.delete_activity, name='delete_activity'),
        # Legacy paths, should not be used in new code
        path('<int:area_id>/description', views.edit_area, name='area_description'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
        path('create/<int:area_id>', views.create, name='create'),
        path('<int:item_id>/delete', views.delete, name='delete'),
]

tutorial/urls.py
from django.urls import path
from . import views

app_name = 'tutorial'
urlpatterns = [
        path('', views.index, name='index'),
        path('<int:tutorial_stage>', views.tutorial, name='tutorial'),
]

explore/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import (
    BooleanField,
    CharField,
    DateTimeField,
    ForeignKey,
    IntegerField,
    OneToOneField,
    TextField,
)
from django.db.models.signals import post_save

# Create your models here.

class News(models.Model):
    created_at = DateTimeField(auto_now_add=True)
    text = TextField(blank=True, default='')

    def __str__(self):
        return self.text

class Area(models.Model):

    created_at = DateTimeField(auto_now_add=True)
    creator = ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
    )
    title = CharField(max_length=512)
    description = TextField(blank=True, default='')
    published = BooleanField(default=False)

    def __str__(self):
        return self.title

class Activity(models.Model):

    created_at = DateTimeField(auto_now_add=True)
    creator = ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL)
    activity_text = CharField(max_length=512)
    area = ForeignKey(Area, null=True, on_delete=models.CASCADE)
    creator_only = BooleanField(default=False)

    def __str__(self):
        return self.activity_text

    def tidy(user, area):
        Activity.objects.filter(creator_only=True, creator=user).exclude(area=area).delete()

class Connection(models.Model):
    created_at = DateTimeField(auto_now_add=True)
    creator = ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL)
    area_from = ForeignKey(Area, on_delete=models.CASCADE, related_name='outgoing')
    area_to = ForeignKey(Area, on_delete=models.CASCADE, related_name='incoming', null=True)
    title = CharField(max_length=512)

    def __str__(self):
        return f'{self.area_from.id} : {self.title} -> {self.area_to.id})'

class Score(models.Model):
    user = OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        on_delete=models.CASCADE)
    total = IntegerField(default=0)

    def user_save(sender, instance, **kwargs):
        try:
            Score.objects.get(user=instance)
        except ObjectDoesNotExist:
            Score(user=instance).save()
	
# Ensure each user has a score entry
post_save.connect(Score.user_save, sender=User)

explore/forms.py
from django import forms

class SelectAreaForm(forms.Form):
    area_attrs = {
        'autofocus': 'autofocus',
        'autocomplete': 'off',
    }
    area_title = forms.CharField(
        max_length=512,
        label='Area Name ',
        label_suffix='>',
        widget=forms.TextInput(attrs=area_attrs),
    )

class CommandForm(forms.Form):
    command_attrs = {
        'autofocus': 'autofocus',
        'autocomplete': 'off',
    }
    command_text = forms.CharField(
        max_length=512,
        label='>',
        widget=forms.TextInput(attrs=command_attrs),
    )

class AreaForm(forms.Form):
    attrs = {
        'cols': '80',
        'autofocus': 'autofocus'
    }
    title = forms.CharField(label='Title')
    description = forms.CharField(
        label='Description',
        widget=forms.Textarea(attrs=attrs),
        required=False,
    )

class ConnectionForm(forms.Form):
    attrs = {
        'autofocus': 'autofocus',
        'autocomplete': 'off',
    }
    destination_title = forms.CharField(
        label='Destination Area',
        label_suffix=' >',
        widget=forms.TextInput(attrs=attrs),
    )

class DeleteForm(forms.Form):
    pass

explore/views.py
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError

from .models import Activity, Area, Connection, News
from player.models import Player

from .forms import (
        AreaForm,
        CommandForm,
        ConnectionForm,
        DeleteForm,
        SelectAreaForm,
)
from .interpreter import Interpreter

def index(request):

    # Get lobby area
    try:
        lobby = Area.objects.get(title="Lobby")
    except ObjectDoesNotExist:
        lobby = Area(title="Lobby")
        lobby.save()

    # Check if user has a current location
    try:
        player = request.user.player
        location = player.location
        if location != lobby:
            return redirect('explore:area', area_id=location.id)
    except AttributeError:
        pass

    # If data has been posted, handle the command
    if request.method == 'POST':
        # Create and validate a form
        form = CommandForm(request.POST)
        if form.is_valid():
            # Create the interpreter
            i = Interpreter(
                {'user': request.user, 'area': lobby},
                request,
            )
            path = i.execute(form.cleaned_data["command_text"])
            if path is not None:
                return HttpResponseRedirect(path)

    # Get a list of activities
    if request.user.is_authenticated:
        for_user = Q(creator_only=False) | Q(creator=request.user)
    else:
        for_user = Q(creator_only=False)
    activities = Activity.objects.filter(area=lobby).filter(for_user).order_by('-created_at')

    # Construct context variables and render template
    top_users = User.objects.exclude(username='admin').order_by('-score__total')[:5]
    players = lobby.player_set.all()
    if request.user.is_authenticated:
        players = players.exclude(user=request.user)
    context = {
        'user': request.user,
        'area': lobby,
        'areas': Area.objects.filter(published=True).order_by('-created_at'),
        'players': players,
        'activities': activities,
        'items': lobby.item_set.all(),
        'top_users': top_users,
        'news': News.objects.order_by('created_at').last(),
        'command_form': CommandForm(label_suffix=''),
    }
    return render(request, 'explore/index.html', context)

def lobby(request):

    # Get lobby area
    try:
        lobby = Area.objects.get(title="Lobby")
    except ObjectDoesNotExist:
        lobby = Area(title="Lobby")
        lobby.save()

    # Set player's current location to lobby
    try:
        player = request.user.player
        player.location = lobby
        player.save()
    except AttributeError:
        pass

    return redirect('explore:index')

def area(request, area_id):

    # Get area object
    area = get_object_or_404(Area, id=area_id)
    if request.user.is_authenticated:
        # Clear activities from other areas
        Activity.tidy(request.user, area)
        # Update player location
        request.user.player.location = area
        request.user.player.save()

    # If data has been posted, handle the command
    if request.method == 'POST':
        # Create and validate a form
        form = CommandForm(request.POST)
        if form.is_valid():
            # Create the interpreter
            i = Interpreter({'user': request.user, 'area': area}, request)
            path = i.execute(form.cleaned_data["command_text"])
            if path is not None:
                return HttpResponseRedirect(path)

    # Get a list of activities
    if request.user.is_authenticated:
        for_user = Q(creator_only=False) | Q(creator=request.user)
    else:
        for_user = Q(creator_only=False)
    activities = Activity.objects.filter(area=area).filter(for_user).order_by('-created_at')[:24]

    # Build context and render the template
    players = area.player_set.all()
    if request.user.is_authenticated:
        players = players.exclude(user=request.user)
    context = {
       'user': request.user,
       'area': area,
       'activities': activities,
       'players': players,
       'items': area.item_set.all(),
       'subtitle': area.title,
       'command_form': CommandForm(label_suffix=''),
       'show_how_to_play': True,
    }
    return render(request, 'explore/room.html', context)

def json_activity(request, area_id):
    # Get area object
    area = get_object_or_404(Area, id=area_id)
    # Get a list of activities
    if request.user.is_authenticated:
        for_user = Q(creator_only=False) | Q(creator=request.user)
    else:
        for_user = Q(creator_only=False)
    activities = Activity.objects.filter(area=area).filter(for_user).order_by('-created_at')[:24]
    return JsonResponse({"activities": [str(a) for a in activities]})


@login_required
def create_area(request, area_title=''):

    # Look up area object
    try:
        area = Area.objects.get(title__iexact=area_title.strip())
        messages.add_message(request, messages.ERROR, f'Area "{area_title}" already exists.')
        # Default to request url
        url = request.path
        # Check for 'next' variable in get and post
        try:
            url = request.GET['next']
        except MultiValueDictKeyError:
            pass
        try:
            url = request.POST['next']
        except MultiValueDictKeyError:
            pass
        return HttpResponseRedirect(url)
    except ObjectDoesNotExist:
        pass

    # Check for changes
    if request.method == 'POST':
        # Create and validate a form
        form = AreaForm(request.POST)
        if form.is_valid():
            new_title = request.POST.get('title', '').strip()
            new_description = request.POST.get('description' '').strip()
            area = Area(title=new_title, description=new_description, creator=request.user)
            area.save()
            url = request.POST.get('next', reverse('explore:area', args=[area.id]))
            return HttpResponseRedirect(url)

    # Build edit form
    initial =  {
        'title': area_title,
    }
    area_form = AreaForm(initial=initial)
    if len(area_title) > 0:
        # Focus description if title already exists
        area_form.fields['description'].widget.attrs['autofocus'] = 'autofocus'
    else:
        # Otherwise focus title
        area_form.fields['title'].widget.attrs['autofocus'] = 'autofocus'


    # Render edit form
    context = {
        'area_form': area_form,
        'user': request.user,
    }
    return render(request, 'explore/area_detail.html', context)

@login_required
def edit_area(request, area_id):

    # Look up area object
    area = get_object_or_404(Area, id=area_id)

    # Check for changes
    if request.method == 'POST':
        # Create and validate a form
        form = AreaForm(request.POST)
        if form.is_valid():
            new_title = request.POST.get('title', '').strip()
            # Check whether title is already taken
            other_area = Area.objects.filter(title__iexact=new_title).exclude(id=area_id).count()
            if other_area == 0:
                area.title = new_title
            else:
                messages.add_message(request, messages.ERROR, f'Couldn\'t change area name, "{new_title}" already exists.') 
            area.description = request.POST.get('description', '')
            area.save()
            # Update scores
            if area.creator and request.user.id != area.creator.id:
                score = area.creator.score
                score.total += 10
                score.save()
            return HttpResponseRedirect(reverse('explore:area', args=[area_id]))

    # Render edit form
    initial =  {
        'description': area.description,
        'title': area.title,
    }
    context = {
        'area': area,
        'area_form': AreaForm(initial=initial),
        'user': request.user,
    }
    return render(request, 'explore/area_detail.html', context)

@login_required
def new_connection(request, source_id, title):

    # Look up source area object
    area_from = get_object_or_404(Area, id=source_id)

    # Check whether connection exists
    try:
        connection = Connection.objects.get(area_from=area_from, title=title)
        messages.add_message(request, messages.ERROR, f'Unable to create connection "{title}": already exists')
        if request.GET['next']:
            url = request.GET['next']
        else:
            url = reverse('explore:area', args=[area_from.id])
        return HttpResponseRedirect(url)
    except ObjectDoesNotExist:
        pass

    # Check for changes
    if request.method == 'POST':
        # Create and validate a form
        form = ConnectionForm(request.POST)
        if form.is_valid():
            area_to, created = Area.objects.get_or_create(
                title=form.cleaned_data['destination_title'],
                defaults={ 'creator': request.user })
            connection, created = Connection.objects.get_or_create(
                title=title,
                area_from=area_from,
                defaults={ 'area_to': area_to, 'creator': request.user }
            )
            if created:
                connection.save()
                # Update scores
                if area_from.creator and area_from.creator != request.user:
                    score = area_from.creator.score
                    score.total += 10
                    score.save()
                if area_to.creator and area_to.creator != request.user:
                    score = area_to.creator.score
                    score.total += 10
                    score.save()

explore/templates/explore/area_detail.html
{% extends 'base.html' %}

{% block dashboard %}
<div id="dashboard">
  {% if user.is_authenticated %}
  User: {{ user.username}} - Score: {{ user.score.total|stringformat:"09d" }}
  {% else %}
  <a href="{% url 'login' %}?next={{ request.path }}">login</a>
  or
  <a href="{% url 'register' %}?next={{ request.path }}">register</a>  
  {% endif %}
</div>
{% endblock %}

{% block content %}
  <div id="info" class="section">
    {% if area %}
      Edit Area: {{ area.title }}
    {% else %}
      Create Area
    {% endif %}
  </div>
  <div id="description" class="section form">
    <form method="post">
      {% csrf_token %}
      {{ area_form.as_p }}
      {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}"/>
      {% endif %}
      <input type="submit" value="Update"/>
      <button onclick="window.history.back();">Cancel</button>
    </form>
  </div>
{% endblock %}

explore/templates/explore/connection_detail.html
{% extends 'base.html' %}

{% block dashboard %}
<div id="dashboard">
  {% if user.is_authenticated %}
  User: {{ user.username}} - Score: {{ user.score.total|stringformat:"09d" }}
  {% else %}
  <a href="{% url 'login' %}?next={{ request.path }}">login</a>
  or
  <a href="{% url 'register' %}?next={{ request.path }}">register</a>  
  {% endif %}
</div>
{% endblock %}
{% block content %}
  <div id="info" class="section">
    {{ area_from.title}} : {{ title }}
  </div>
  {% if messages %}
  <ul id="messages" class="section">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
  <div id="destination" class="section">
    <form method="post">
      {% csrf_token %}
      {{ connection_form }}
      <input type="hidden" name="next" value="{{ request.GET.next }}"/>
      <input type="submit" value="Update"/>
      <button onclick="window.history.back();">Cancel</button>
    </form>
  </div>
{% endblock %}

explore/templates/explore/delete.html
{% extends 'base.html' %}

{% block dashboard %}
<div id="dashboard">
  {% if user.is_authenticated %}
  User: {{ user.username}} - Score: {{ user.score.total|stringformat:"09d" }}
  {% else %}
  <a href="{% url 'login' %}?next={{ request.path }}">login</a>
  or
  <a href="{% url 'register' %}?next={{ request.path }}">register</a>  
  {% endif %}
</div>
{% endblock %}

{% block content %}
  <div id="info" class="section">
    Delete {{ type }}: {{ title }}
  </div>
  <div id="confirm" class="section">
    <p>Are you sure?</p>
    <form method="post">
      {% csrf_token %}
      {{ form }}
      <input type="hidden" name="next" value="{{ request.GET.next }}"/>
      <input type="submit" value="Delete"/>
      <button onclick="window.history.back();return false;">Cancel</button>
    </form>
  </div>
{% endblock %}

explore/templates/explore/index.html
{% extends 'base.html' %}

{% load static %}

{% block scripts %}
<script type="text/javascript" src="{% static 'activity.js' %}"></script>
<script type="text/javascript">
  console.log('Enabling ajax');
  Activity.enableAjax({{ area.id }});
</script>
{% endblock %}

{% load player_extras %}

{% block dashboard %}
<div id="dashboard">
  {% if user.is_authenticated %}
  User: {{ user.username}} - Score: {{ user.score.total|stringformat:"09d" }}
  {% else %}
  <a href="{% url 'login' %}?next={{ request.path }}">login</a>
  or
  <a href="{% url 'register' %}?next={{ request.path }}">register</a>  
  {% endif %}
</div>
{% endblock %}

{% block content %}
  <div class="row">
    <div id="about">
      <p>
      Welcome to Adventure.TXT, a collaborative multiplayer text adventure.
      The game and story are created by the users, and always evolving.
      Your score increases as other players interact with parts of the world you create.
      Keep an eye out on the lobby for news about new features.
      <a href="{% url 'tutorial:index' %}">Tutorial</a>.
      <a href="/guide">Player's Guide</a>.
      </p>
    </div>
    <div id="top-players">
      <h2>Top Players</h2>
      <table>
        <thead>
          <th>Players</th>
          <th>Score</th>
        </thead>
        <tbody>
        {% for u in top_users %}
          <tr><td>{{ u.username }}</td><td>{{ u.score.total|stringformat:"09d" }}</tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% if news %}
  <div id="news" class="section"><h2>News</h2><div>{{ news }}</div></div>
  {% endif %}

  <div class="section">
    <h2>Lobby</h2>

    {% if area.description %}
      <div id="area-description">{{ area.description }}</div>
    {% endif %}
    {% if items %}
       <ul id="area-items">
       {% for item in items %}
           <li>{{ item.short_description }}</li>
       {% endfor %}
       </ul>
    {% endif %}
    {% if players %}
       <ul id="area-players">
       {% for player in players.all %}
           <li><strong>{{ player.user.username }}</strong> {% player_status player %}</li>
       {% endfor %}
       </ul>
    {% endif %}
  </div>
  {% if area.outgoing.count > 0 %}
  <div id="area-exits" class="section">
      Connections:
      {% for c in area.outgoing.all %}
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="command_text" value="{{ c.title }}"/>
          <button type="submit">{{ c.title }}</button>{% if not forloop.last %},{% endif %}
        </form>
      {% endfor %}
  </div>
  {% endif %}
  {% if messages %}
  <ul id="messages" class="section">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
  {% if activities.count > 0 %}
    <div id="activity" class="section">
    {% for activity in activities %}
      <div class="activity">
        {{ activity.activity_text }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
  <div id="actions" class="section">
      <form method="post">
        {% csrf_token %}
        {{ command_form }}
      </form>
  </div>

  <div class="row">
    <div id="recently-created">
      <h3>Recently Created</h3>
      {% if areas %}
        <ul class="text-list">
        {% for a in areas %}
          <li>
            <form method="post">
              {% csrf_token %}
              <input type="hidden" name="command_text" value="warp {{ a.title }}"/>
              <input type="submit" value="{{ a.title }}"/>
            </form>
          </li>
        {% endfor %}
        </ul>
      {% else %}
        <p>No areas have been published yet.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

explore/templates/explore/room.html
{% extends 'base.html' %}

{% load static %}
{% load player_extras %}

{% block scripts %}
<script type="text/javascript" src="{% static 'activity.js' %}"></script>
<script type="text/javascript">
  console.log('Enabling ajax');
  Activity.enableAjax({{ area.id }});
</script>
{% endblock %}

{% block og_description %}<meta property="og:description" content="{{ area.title }} - {{ area.description }}" />{% endblock %}


{% block dashboard %}
<div id="dashboard">
  {% if user.is_authenticated %}
  User: {{ user.username}} - Score: {{ user.score.total|stringformat:"09d" }}
  {% else %}
  <a href="{% url 'login' %}?next={{ request.path }}">login</a>
  or
  <a href="{% url 'register' %}?next={{ request.path }}">register</a>  
  {% endif %}
</div>
{% endblock %}

{% block content %}
  <div id="info" class="section">
    <p>{{ area.title }}</p>
    {% if area.description %}
      <div id="area-description">{{ area.description }}</div>
    {% endif %}
    {% if items %}
       <ul id="area-items">
       {% for item in items %}
           <li>{{ item.short_description }}</li>
       {% endfor %}
       </ul>
    {% endif %}
    {% if players %}
       <ul id="area-players">
       {% for player in players.all %}
           <li><strong>{{ player.user.username }}</strong> {% player_status player %}</li>
       {% endfor %}
       </ul>
    {% endif %}
  </div>
  {% if connections %}
    <div id="area-exits" class="section">
        Connections:
        {% for c in connections %}
          <form method="post">
            {% csrf_token %}
            <input type="hidden" name="command_text" value="c"/>
            <button type="submit">{{ c }}</button>{% if not forloop.last %},{% endif %}
          </form>
        {% endfor %}
    </div>
  {% else %}
    {% if area.outgoing.count > 0 %}
    <div id="area-exits" class="section">
        Connections:
        {% for c in area.outgoing.all %}
          <form method="post">
            {% csrf_token %}
            <input type="hidden" name="command_text" value="{{ c.title }}"/>
            <button type="submit">{{ c.title }}</button>{% if not forloop.last %},{% endif %}
          </form>
        {% endfor %}
    </div>
    {% endif %}
  {% endif %}
  {% if messages %}
  <ul id="messages" class="section">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
  {% if activities.count > 0 %}
    <div id="activity" class="section">
    {% for activity in activities %}
      <div class="activity">
        {{ activity.activity_text }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
  <div id="actions" class="section">
    <form method="post">
      {% csrf_token %}
      {{ command_form }}
    </form>
  </div>
  {% if show_how_to_play %}
  <div id="tutorial">
    <h2>How to Play</h2>
    <p>
      This game is built by the players.
      Your score increases every time another player interacts with
      a part of the world you created.
    </p>
    <p>
      Some examples:<br/>
      &gt; edit area<br/>
      &gt; create connection north<br/>
      &gt; north<br/>
      &gt; Hello, World!
    </p>
    <p>
      Or try the <a href="{% url 'tutorial:index' %}">tutorial</a>.
    </p>
  </div>
  {% endif %}
{% endblock %}